CREATE TABLE THREAD (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(200) NOT NULL,
  TAGS VARCHAR(600) NOT NULL,
  CREATED_ACCOUNT_ID BIGINT NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  UPDATED_TIME TIMESTAMP NOT NULL
);

INSERT INTO THREAD (
  TITLE,
  TAGS,
  CREATED_ACCOUNT_ID,
  CREATED_TIME,
  UPDATED_TIME
) VALUES (
  'Today''s dinner',
  'food,cooking',
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

CREATE TABLE POST (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  THREAD_ID BIGINT(20) NOT NULL,
  CONTENT VARCHAR(500) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY BIGINT(20) NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY BIGINT(20) NOT NULL
);

INSERT INTO POST (
  THREAD_ID,
  CONTENT,
  CREATED_AT,
  CREATED_BY,
  UPDATED_AT,
  UPDATED_BY
) VALUES (
  1,
  'yahoo',
  CURRENT_TIMESTAMP,
  1,
  CURRENT_TIMESTAMP,
  1
);
